### ISSUE TITLE
I am not able to train my CNN due to this error and it automatically gets terminated

### ISSUE THREAD

**Issue by chavangorakh1999** [AskNowQA/KrantikariQA#19]
<img width="646" alt="Screenshot 2019-12-22 at 7 15 58 PM" src="https://user-images.githubusercontent.com/51993140/71333673-e8244280-2560-11ea-9c1a-a338f6d46cd4.png">

**Comment by geraltofrivia** [comment]
Hi, could you give me some more context on this? (i) What file is this? Also (ii) whether you're running this on GPU/CPU? and (iii) what Tensorflow version?
